name: Vite Deploy to Subtree
run-name: Vite Deploy to Subtree
on: [push]

jobs:
  Build-and-Push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - run: |
        echo "${{  github.repository }} cloned"
        npm install
        npm run build

      - run: |
        git config --global user.email "csperando@gmail.com"
        git config --global user.name "Coleman Sperando"
        git add dist -f
        git commit -m "actions automated commit latest dist/"
        git subtree push --prefix dist origin gh-pages
