name: Vite Deploy to Subtree
run-name: Vite Deploy to Subtree
on: [push]

jobs:
  Build-and-Push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.token }}

      - name: Build dist/ directory
        run: |
          echo "${{  github.repository }} cloned"
          npm install
          npm run build
          ls

      - name: Update config and commit changes
        run: |
          git config --global user.email "csperando@gmail.com"
          git config --global user.name "Coleman Sperando"
          git add dist -f
          git commit -m "actions automated commit latest dist/"

      - name: Push to subtree
        run:
          git push origin `git subtree push --prefix dist origin`:gh-pages --force
