name: CI
run-name: Build Vite Application
on: [push]

jobs:
  Build-and-Push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.token }}

      - name: Update config
        run: |
          git config --global user.email "csperando@gmail.com"
          git config --global user.name "Coleman Sperando"
          git config --global pull.rebase true
          git status
          git branch -l
          git remote -v

      - name: Clean up subtree conflicts
        run: |
          git checkout -B gh-pages
          git fetch origin gh-pages
          git reset --hard origin/gh-pages
          git checkout main
        # git read-tree --prefix=dist/ -u origin/gh-pages
        # git status
        # git add dist -f
        # git commit -m "actions automated commit read-tree"

      - name: Build dist/ directory
        run: |
          echo "${{  github.repository }} cloned"
          npm install
          npm run build
          ls

      - name: Force commit updated dist
        run: |
          git add dist -f
          git commit -m "actions automated commit build dist/"

      - name: Push to subtree
        run: |
          git push origin `git subtree split --prefix=dist/ main`:origin/gh-pages --force
