name: CI
run-name: Build Vite Application
on: [push]

jobs:
  Build-and-Push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.token }}

      - name: Update config
        run: |
          git config --global user.email "csperando@gmail.com"
          git config --global user.name "Coleman Sperando"

      - name: Build dist/ directory
        run: |
          echo "${{  github.repository }} cloned"
          npm install
          npm run build

      # if gh-pages does not exist: execute `git subtree push --prefix dist/ origin gh-pages`

      - name: Force commit updated dist
        run: |
          git add dist -f
          git commit -m "actions automated commit build dist/"

      # Thank you: https://clontz.org/blog/2014/05/08/git-subtree-push-for-deployment/
      - name: Push to subtree
        run: |
          git push origin `git subtree split --prefix=dist/ main`:gh-pages --force
